<a href="https://colab.research.google.com/github/teahojung/goodjob/blob/main/stupid0802.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#### 7.2.1 중복제거하기



In [ ]:
data = pd.DataFrame({'k1' : ['one', 'two'] * 3 + ['two'],
                     'k2' : [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data2 = pd.DataFrame({'k1' : ['one', 'two'] * 3 + ['two'],
                     'k2' : [1, 1, 2, 3, 3, 4, 5]})
data2

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   5

In [ ]:
data2.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [ ]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)

data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [ ]:
data.drop_duplicates()

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [ ]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [ ]:
data.drop_duplicates(['k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [ ]:
data.drop_duplicates(['v1'])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [ ]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 7.2.2 함수나 매핑을 이용해서 데이터 변형하기

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                       'Pastrami', 'corned beef', 'Bacon',
                       'pastrami', 'honey ham', 'nova lox'],
                     'ounces' : [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon',
    'corned beef': 'cow' 
}

In [ ]:
lowercased = data['food'].str.lower()

In [ ]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [ ]:
data['animal'] = lowercased.map(meat_to_animal)

In [ ]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 7.2.3 값 치환하기

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [ ]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data.replace({-999:np. nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 7.2.4 축색인 이름 바꾸기

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
transform = lambda x: x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [ ]:
data.index = data.index.map(transform)

In [ ]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [ ]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 7.2.5 개별화와 양자화

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [ ]:
cats = pd.cut(ages, bins)

cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [ ]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [ ]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [ ]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [ ]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [ ]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
data = np.random.rand(20)

In [ ]:
pd.cut(data, 4, precision=2)

[(0.51, 0.75], (0.51, 0.75], (0.51, 0.75], (0.28, 0.51], (0.28, 0.51], ..., (0.28, 0.51], (0.51, 0.75], (0.046, 0.28], (0.28, 0.51], (0.046, 0.28]]
Length: 20
Categories (4, interval[float64]): [(0.046, 0.28] < (0.28, 0.51] < (0.51, 0.75] < (0.75, 0.98]]

### 7.2.6 특잇값을 찾고 제외하기

In [ ]:
data = np.random.randn(1000)

In [ ]:
cats = pd.qcut(data, 4)

In [ ]:
cats

[(0.69, 2.672], (-2.862, -0.66], (-2.862, -0.66], (-0.0344, 0.69], (-2.862, -0.66], ..., (-2.862, -0.66], (-0.0344, 0.69], (-2.862, -0.66], (0.69, 2.672], (-0.0344, 0.69]]
Length: 1000
Categories (4, interval[float64]): [(-2.862, -0.66] < (-0.66, -0.0344] < (-0.0344, 0.69] <
                                    (0.69, 2.672]]

In [ ]:
pd.value_counts(cats)

(0.69, 2.672]       250
(-0.0344, 0.69]     250
(-0.66, -0.0344]    250
(-2.862, -0.66]     250
dtype: int64

In [ ]:
catss = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

In [ ]:
catss

[(-0.0344, 1.273], (-1.299, -0.0344], (-2.862, -1.299], (-0.0344, 1.273], (-1.299, -0.0344], ..., (-1.299, -0.0344], (-0.0344, 1.273], (-2.862, -1.299], (1.273, 2.672], (-0.0344, 1.273]]
Length: 1000
Categories (4, interval[float64]): [(-2.862, -1.299] < (-1.299, -0.0344] < (-0.0344, 1.273] <
                                    (1.273, 2.672]]

In [ ]:
pd.value_counts(catss)

(-0.0344, 1.273]     400
(-1.299, -0.0344]    400
(1.273, 2.672]       100
(-2.862, -1.299]     100
dtype: int64

특잇값

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))

data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.029064    -0.005265     0.007500    -0.048782
std       1.011076     0.976153     0.997141     0.982714
min      -3.711912    -2.710234    -3.220917    -3.155784
25%      -0.692610    -0.693941    -0.646375    -0.694259
50%      -0.054337    -0.005483     0.005011     0.002011
75%       0.615798     0.682388     0.711320     0.596732
max       3.106588     2.759354     4.046886     3.017358

In [ ]:
col = data[2]

col[np.abs(col) > 3]

86     3.171485
460    4.046886
575   -3.220917
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
45  -3.711912 -2.605845  1.487368  0.082075
86   0.204053 -0.342809  3.171485 -0.242196
105 -3.035643 -1.134620 -0.727103  1.116473
165  3.103417  0.104769  0.622204  1.005418
221 -0.208586  1.273138 -1.313331 -3.155784
374  3.106588  0.048476 -1.064089  0.114561
460 -0.185692  1.350471  4.046886 -0.784635
575  1.368178  0.034046 -3.220917 -0.140812
774 -3.592423 -0.793028 -0.348492 -0.631800
842  0.659827  0.804396  0.244426  3.017358

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3

data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027934    -0.005265     0.006503    -0.048643
std       1.006055     0.976153     0.992212     0.982180
min      -3.000000    -2.710234    -3.000000    -3.000000
25%      -0.692610    -0.693941    -0.646375    -0.694259
50%      -0.054337    -0.005483     0.005011     0.002011
75%       0.615798     0.682388     0.711320     0.596732
max       3.000000     2.759354     3.000000     3.000000

In [ ]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0 -1.0 -1.0
2 -1.0 -1.0  1.0  1.0
3  1.0  1.0  1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

### 7.2.7 치환과 임의 샘플링

In [ ]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

sampler = np.random.permutation(5)

sampler

array([1, 2, 0, 3, 4])

In [ ]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19

In [ ]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

In [ ]:
df.sample(n=6)

ValueError: ignored

In [ ]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

1    7
1    7
4    4
0    5
3    6
2   -1
4    4
3    6
2   -1
3    6
dtype: int64

### 7.2.8 표시자/더미 변수 계산하기

In [ ]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [ ]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [ ]:
df_with_dummy = df[['data1']].join(dummies)

In [ ]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

### Movielens case

In [ ]:
import io
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
mnames = ['movie_id', 'title', 'genres']

movies = pd.read_table('/content/drive/MyDrive/pydata/datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)

movies[:10]

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [ ]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

genres = pd.unique(all_genres)

genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [ ]:
zero_matrix = np.zeros((len(movies), len(genres)))

dummies = pd.DataFrame(zero_matrix, columns=genres)

In [ ]:
gen = movies.genres[0]

gen.split('|')

['Animation', "Children's", 'Comedy']

In [ ]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [ ]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [ ]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [ ]:
np.random.seed(12345)

values = np.random.rand(10)

values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [ ]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0